React2 Reiteration
HackYourFuture-CPH/React pull request #69
Opened 2024-09-25 12:34 UTC by chezzoba

Made changes to React 2.

2024-09-30 07:46 UTC, adamblanchard requested changes

2024-09-30 07:46 UTC, adamblanchard commented on readme.md
> +### [React 2](/react2/readme.md) (2 weeks)
"2 weeks" here conflicts a little with the link it goes to.

I suggest we change it here to 3 weeks and include the meal sharing bit in this section too, like:

```
### [React 2](/react2/readme.md) (3 weeks)
...
In the third week, you'll get to implement the UI for your Meal Sharing app...
```

2024-09-30 07:46 UTC, adamblanchard commented on react1/readme.md
> +| Week | Topic | Preparation | Lesson plan | Homework |
For consistency with the other modules, can the homework links go to the readme instead of directly to the repo?

2024-10-02 21:30 UTC, markitosha reviewed
This is an amazing piece of work you've done here!
I have a couple of thoughts regarding changes for the program, and would like to discuss them here. Disclaimer: if I sound too opinionated or harsh somewhere, perhaps it's a language barrier and I'm sorry 😅 

---

While I agree that React 2 should focus on Next.js, I’m not sure if introducing it in React 1 is the best approach.

In my opinion, React 1 should stick to plain React (using Vite or something similar) because it allows students to learn the fundamentals without the added complexity of a framework. Introducing Next.js too early could lead to framework-specific errors that are difficult to address in the first few weeks. (I still encounter them even on small projects, and I don’t think we want to teach people to ignore warnings 😄 ). Plain React, as a library, is simple and effective for mastering basics. Also we might focus only on core basics in the first week and we won't have to introduce routing that quickly. 

From a practical standpoint, many companies still use plain React or their own custom SSR solutions. By not pushing students towards a framework too early, we could help make them more adaptable to various approaches (although I admit this point is somewhat theoretical 😄).

As the rest of the program,
- I found missing a ["server actions"](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations) topic for Next.js (if we want them to use SSR -- this is the way)
- That would be nice to mention "custom hooks" (very small topic, but can decrease a code complexity a lot simply by code splitting)
- This one I'm not sure about: other concepts, such as easy optimizations (useMemo, useCallback, React.memo) and authentication, can also be introduced once students have a solid foundation. But maybe they are too advanced (but usually wanted for the jobs) 

Again, I'm here almost "first day" and don't know students very well, so everything here is open for discussion!

2024-10-03 08:41 UTC, chezzoba commented on react1/week3/lesson-plan.md
> +* `key` property
Yes, thanks! Removed that exercise there.

2024-10-03 08:41 UTC, chezzoba commented on react1/week2/lesson-plan.md
> +* CSS modules in Next.js
You're right. Removed it here.

2024-10-07 09:24 UTC, adamblanchard approved these changes

2024-10-07 09:24 UTC, merged